### ISSUE TITLE
Evitar faltas gramaticales en la memoria

### ISSUE THREAD

**Issue by migueorg** [migueorg/One-touch-music-streaming-TFG-ETSIIT#17]
Atendiendo a la HU #14, la memoria ha de estar libre de errores gramaticales y ortográficos. Por lo que se buscará y decidirá alguna forma de asegurar dicha característica.

**Comment by JJ** [comment]
Una vez más, un issue es un problema. Si lo formulas como una tarea, estás descartando automáticamente otras posibles soluciones (como podría ser montar un hook de git local, o algo así). El problema en este caso es la calidad de la memoria, según una de las rúbricas de la evaluación. Y es un problema que tienes que resolver para el cliente #14 
Tendrás que ver las diferentes opciones que hay; en otros TFGs han usado textidote, que es también comprobador gramatical, pero puedes buscar a ver si ahora hay algún otro que vaya bien.
También tienes que compilar el LaTeX para ver si la estructura está bien. Como te digo, fijándote sólo en una solución a un problema (que no está formulado) quitas el foco de lo principal, que es la calidad y el hacer las cosas para el tribunal.
