### ISSUE TITLE
Expresar contexto y necesidades del problema a solucionar

### ISSUE THREAD

**Issue by migueorg** [migueorg/One-touch-music-streaming-TFG-ETSIIT#6]
Avanzando en la HU #14, a partir de los usuarios presentados previamente, ampliar cuáles son las necesidades y el contexto de los usuarios que usarán la aplicación.

**Comment by JJ** [comment]
Recuerda que todos los issues tienen que ser un problema, y tienen que responder a una HU. En este caso, la HU es #14 (que supongo que es el tribunal). En este caso, se trata de expresar claramente cuales son las necesidades y el contexto de los usuarios para poder comenzar correctamente el desarrollo del proyecto.
