### ISSUE TITLE
Concretar los realeses que se harán

### ISSUE THREAD

**Issue by migueorg** [migueorg/One-touch-music-streaming-TFG-ETSIIT#8]
A partir de las historias de usuario, determinar los productos mínimamente viables que se irán entregando con el tiempo. Esto se documentará para atender a la HU #14.

**Comment by JJ** [comment]
Salvo que te refieras a añadirlos a la memoria, esto no sería un issue (tampoco es un problema). Recuerda que los issues se refieren sólo a cambios en el repositorio.
